In [1]:
import numpy as np
from datetime import date, timedelta

# 1. Create a 3x3x3 array with random values

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.92018253, 0.9462101 , 0.08866326],
        [0.34621998, 0.97434152, 0.22816779],
        [0.00171708, 0.92034411, 0.23989054]],

       [[0.79910811, 0.82666858, 0.81940171],
        [0.47085698, 0.169482  , 0.95041981],
        [0.9530438 , 0.85504196, 0.81066485]],

       [[0.7448719 , 0.87951158, 0.32305599],
        [0.39311085, 0.61945145, 0.00501185],
        [0.96398918, 0.46502748, 0.14995565]]])

# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[ 1.00997093, -1.49999012, -0.75562453,  0.39560508,  0.0949606 ],
       [ 1.4173252 ,  0.79505885, -0.39810692,  0.17006244, -0.68756739],
       [-0.68068122,  0.74973123, -0.43300095,  1.14668103,  0.55692346],
       [ 1.53899811, -1.56165608,  1.0633494 ,  1.29670198, -1.80475089],
       [ 0.67778937, -0.56446093, -0.33802387, -0.50765651, -1.68163825]])

# 5. How to find common values between two arrays

In [6]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([0, 3, 5, 7, 9])

# 6. How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-07-25 2020-07-26 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [8]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.72349988 0.56100936 0.5439576 ]
 [0.72161517 0.06484549 0.96635342]
 [0.43090123 0.53361107 0.31306906]]


Array2:
[[0.15146812 0.61919583 0.43958681]
 [0.46751162 0.36316454 0.70025903]
 [0.06136684 0.06537193 0.50752948]]


Equality: False


# 8. Create random vector of size 10 and replace the maximum value by 0

In [9]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.86283077, 0.9448153 , 0.37678223, 0.2066809 , 0.40195204,
       0.72151847, 0.37559519, 0.59637933, 0.        , 0.53120295])

# 9. How to print all the values of an array?

In [10]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10. Subtract the mean of each row of a matrix

In [11]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[ 0.17072886, -0.19843708,  0.02770823],
       [ 0.46266963, -0.23186064, -0.23080898],
       [ 0.05214496,  0.19646833, -0.24861329]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([5., 2., 1., 5., 2.])

# 12. How to get the diagonal of a dot product?

In [13]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([74, 28, 28])

# 13. How to find the most frequent value in an array?

In [15]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[1 1 6 1 0 8 8 4 5 0 5 2 3 7 6 1 3 9 3 9]


1

# 14. How to get the n largest values of an array

In [16]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

0

# 15. How to create a record array from a regular array?

In [18]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])